'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ilce
    Public Property No As Integer
    Public Property IlNo As Integer
    Public Property Kod As Integer
    Public Property Ad As String

    Public Overridable Property Il As Il
    Public Overridable Property Okuls As ICollection(Of Okul) = New HashSet(Of Okul)

End Class
