'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class MEBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MEBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ils() As DbSet(Of Il)
    Public Overridable Property Ilces() As DbSet(Of Ilce)
    Public Overridable Property Okuls() As DbSet(Of Okul)

    Public Overridable Function GetIlceNo(ilNo As Nullable(Of Integer), ilceNo As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim ilNoParameter As ObjectParameter = If(ilNo.HasValue, New ObjectParameter("IlNo", ilNo), New ObjectParameter("IlNo", GetType(Integer)))

        Dim ilceNoParameter As ObjectParameter = If(ilceNo.HasValue, New ObjectParameter("IlceNo", ilceNo), New ObjectParameter("IlceNo", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("GetIlceNo", ilNoParameter, ilceNoParameter)
    End Function

End Class
