'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Okul
    Public Property No As Integer
    Public Property IlceNo As Integer
    Public Property Ad As String
    Public Property Url As String
    Public Property HakkindaUrl As String
    Public Property KurumKodu As String
    Public Property Tel As String
    Public Property Faks As String
    Public Property Adres As String
    Public Property Vizyon As String
    Public Property Misyon As String
    Public Property Basarilar As String
    Public Property OgretmenSayi As Integer
    Public Property RehberSayi As Integer
    Public Property OgrenciSayi As Integer
    Public Property OgretimSekli As String
    Public Property DersSaati As Integer
    Public Property DesrlikSayi As Integer
    Public Property AtolyeSayi As Integer
    Public Property LabSayi As Integer
    Public Property BtSayi As Integer
    Public Property ResimSayi As Integer
    Public Property MuzikSayi As Integer
    Public Property YabanciDil As Integer
    Public Property Internet As String
    Public Property Hazirlik As Boolean
    Public Property Konferans As Boolean
    Public Property Spor As Boolean
    Public Property Yemekhane As Boolean
    Public Property Misafirhane As Boolean
    Public Property Kutuphane As Boolean
    Public Property Kantin As Boolean
    Public Property Revir As Boolean
    Public Property Bahce As Boolean
    Public Property LojmanSayi As Integer
    Public Property İsinma As String
    Public Property Uzaklik As String
    Public Property Ulasim As String
    Public Property Servis As String
    Public Property Yerlesim As String
    Public Property Kontenjan As String
    Public Property PuanBilgi As String
    Public Property BasariDurumu As String
    Public Property YerlestirmeYuzde As String
    Public Property SporEtkinlik As String
    Public Property BilimEtkinlik As String
    Public Property Projeler As String
    Public Property YurtdisiProje As String

    Public Overridable Property Ilce As Ilce

End Class
