'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Kategori
    Public Property No As Byte
    Public Property Ad As String

    Public Overridable Property Yayınevi As ICollection(Of Yayınevi) = New HashSet(Of Yayınevi)

End Class
