'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class PressInfoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PressInfoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Yayınevi() As DbSet(Of Yayınevi)
    Public Overridable Property Kategoris() As DbSet(Of Kategori)

    Public Overridable Function InsertPress(ad As String, link As String, logo As String, sehir As String) As Integer
        Dim adParameter As ObjectParameter = If(ad IsNot Nothing, New ObjectParameter("Ad", ad), New ObjectParameter("Ad", GetType(String)))

        Dim linkParameter As ObjectParameter = If(link IsNot Nothing, New ObjectParameter("Link", link), New ObjectParameter("Link", GetType(String)))

        Dim logoParameter As ObjectParameter = If(logo IsNot Nothing, New ObjectParameter("Logo", logo), New ObjectParameter("Logo", GetType(String)))

        Dim sehirParameter As ObjectParameter = If(sehir IsNot Nothing, New ObjectParameter("Sehir", sehir), New ObjectParameter("Sehir", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("InsertPress", adParameter, linkParameter, logoParameter, sehirParameter)
    End Function

    Public Overridable Function UpdatePress(no As Nullable(Of Integer), resmiAd As String, tarih As String, yetkili As String, adres As String, tel As String, faks As String, email As String, web As String, bilgi As String, alan As String, iSBN As String) As Integer
        Dim noParameter As ObjectParameter = If(no.HasValue, New ObjectParameter("No", no), New ObjectParameter("No", GetType(Integer)))

        Dim resmiAdParameter As ObjectParameter = If(resmiAd IsNot Nothing, New ObjectParameter("ResmiAd", resmiAd), New ObjectParameter("ResmiAd", GetType(String)))

        Dim tarihParameter As ObjectParameter = If(tarih IsNot Nothing, New ObjectParameter("Tarih", tarih), New ObjectParameter("Tarih", GetType(String)))

        Dim yetkiliParameter As ObjectParameter = If(yetkili IsNot Nothing, New ObjectParameter("Yetkili", yetkili), New ObjectParameter("Yetkili", GetType(String)))

        Dim adresParameter As ObjectParameter = If(adres IsNot Nothing, New ObjectParameter("Adres", adres), New ObjectParameter("Adres", GetType(String)))

        Dim telParameter As ObjectParameter = If(tel IsNot Nothing, New ObjectParameter("Tel", tel), New ObjectParameter("Tel", GetType(String)))

        Dim faksParameter As ObjectParameter = If(faks IsNot Nothing, New ObjectParameter("Faks", faks), New ObjectParameter("Faks", GetType(String)))

        Dim emailParameter As ObjectParameter = If(email IsNot Nothing, New ObjectParameter("Email", email), New ObjectParameter("Email", GetType(String)))

        Dim webParameter As ObjectParameter = If(web IsNot Nothing, New ObjectParameter("Web", web), New ObjectParameter("Web", GetType(String)))

        Dim bilgiParameter As ObjectParameter = If(bilgi IsNot Nothing, New ObjectParameter("Bilgi", bilgi), New ObjectParameter("Bilgi", GetType(String)))

        Dim alanParameter As ObjectParameter = If(alan IsNot Nothing, New ObjectParameter("Alan", alan), New ObjectParameter("Alan", GetType(String)))

        Dim iSBNParameter As ObjectParameter = If(iSBN IsNot Nothing, New ObjectParameter("ISBN", iSBN), New ObjectParameter("ISBN", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UpdatePress", noParameter, resmiAdParameter, tarihParameter, yetkiliParameter, adresParameter, telParameter, faksParameter, emailParameter, webParameter, bilgiParameter, alanParameter, iSBNParameter)
    End Function

End Class
