'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Yayınevi
    Public Property No As Integer
    Public Property Ad As String
    Public Property Link As String
    Public Property Logo As String
    Public Property ResmiAd As String
    Public Property Tarih As String
    Public Property Yetkili As String
    Public Property Adres As String
    Public Property Tel As String
    Public Property Email As String
    Public Property Web As String
    Public Property Bilgi As String
    Public Property Alan As String
    Public Property ISBN As String
    Public Property Sehir As String
    Public Property Faks As String
    Public Property YayineviBirligiNo As Byte
    Public Property bitti As Boolean

    Public Overridable Property Kategoris As ICollection(Of Kategori) = New HashSet(Of Kategori)

End Class
