'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class DiyanetEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DiyanetEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Sehirs() As DbSet(Of Sehir)
    Public Overridable Property Ulkes() As DbSet(Of Ulke)
    Public Overridable Property Vakits() As DbSet(Of Vakit)

    Public Overridable Function InsertCountry(no As Nullable(Of Integer), ad As String) As Integer
        Dim noParameter As ObjectParameter = If(no.HasValue, New ObjectParameter("No", no), New ObjectParameter("No", GetType(Integer)))

        Dim adParameter As ObjectParameter = If(ad IsNot Nothing, New ObjectParameter("Ad", ad), New ObjectParameter("Ad", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("InsertCountry", noParameter, adParameter)
    End Function

    Public Overridable Function InsertState(ulkeNo As Nullable(Of Integer), no As Nullable(Of Integer), ad As String) As Integer
        Dim ulkeNoParameter As ObjectParameter = If(ulkeNo.HasValue, New ObjectParameter("UlkeNo", ulkeNo), New ObjectParameter("UlkeNo", GetType(Integer)))

        Dim noParameter As ObjectParameter = If(no.HasValue, New ObjectParameter("No", no), New ObjectParameter("No", GetType(Integer)))

        Dim adParameter As ObjectParameter = If(ad IsNot Nothing, New ObjectParameter("Ad", ad), New ObjectParameter("Ad", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("InsertState", ulkeNoParameter, noParameter, adParameter)
    End Function

End Class
