'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sehir
    Public Property No As Integer
    Public Property UlkeNo As Integer
    Public Property Ad As String

    Public Overridable Property Vakits As ICollection(Of Vakit) = New HashSet(Of Vakit)

End Class
