'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vakit
    Public Property No As Integer
    Public Property SehirNo As Integer
    Public Property Tarih As Date
    Public Property Hicri As String
    Public Property Imsak As String
    Public Property Gunes As String
    Public Property Ikindi As String
    Public Property Aksam As String
    Public Property Yatsi As String
    Public Property Kible As String

    Public Overridable Property Sehir As Sehir

End Class
